[package]
name = "hive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "2.1.6"
fnv = "1.0.7"
thiserror = "1.0.60"
